apiVersion: v1
kind: Service

metadata:
  name: juice-shop-service
  namespace: devsecops

spec:
  selector:
    app: juice-shop

  type: NodePort

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
